# =============================================================================
# 06_travel_ratio_analysis.R
#
# Attaches population/workplace weights to commuting itineraries, then
# explores the resulting PT/car travel-time ratios: population-weighted
# distributions (the "what share of residents experience ratio X" view,
# rather than treating every OD pair as equally important regardless of who
# lives there), rail vs. non-rail comparison, and competitive/improvement-
# needed itineraries by municipality.
#
# Merged 2026-07-27 from two former scripts (06_add_weights_to_itineraries.R
# + 07_explore_travel_ratios.R): itineraries_weights.csv, written by the
# first half below, had exactly one consumer -- the second half, in the
# very next script -- so splitting the weight-attachment and the analysis
# that immediately reads it back in was pure indirection. Still written to
# disk (as an audit artifact you can inspect directly), but the analysis
# below uses the in-memory object rather than re-reading the CSV.
#
# REQUIRES TO RUN:
#   - pt_itineraries.rds, car_itineraries.rds (written by 05_read_itineraries.R
#     — run that script first if either file is missing)
#   - pop_grid.gpkg (02_distribute_population.R), workplace_grid.gpkg
#     (01_calculate_workplaces.R)
#   - ap.gpkg, gtfs/ztm.zip -- Part 3 only (route-competitiveness map)
#   - itineraries_weights_route_detail.csv -- Part 3 only; a recovered
#     snapshot of an EARLIER itinerary run, NOT regenerated by this script
#     or any other pipeline step (see Part 3's own header comment for why)
#   - od_pair_utils.R, sourced automatically below (not run directly)
# OUTPUT : itineraries_weights.csv
#          Figures/Fig_travelratio_density.png
#          Figures/Fig_travelratio_density_rail.png
#          Figures/Fig_travelratio_density_norail.png
#          Figures/Fig_travelratio_density_rail_vs_norail.png
#          Figures/Fig_travelratio_cumulative_population.png
#          Figures/Fig_travelratio_cumulative_population_rail_vs_norail.png
#          Figures/Fig_travelratio_route_competitiveness.png
#          competitive_by_municipality.csv
#          improvement_by_municipality.csv
# =============================================================================

library(data.table)
library(dplyr)
library(tidyr)
library(sf)
library(ggplot2)
library(tidytransit)
library(maptiles)
library(tidyterra)
library(terra)
library(patchwork)

setwd("C:/Users/wozni/Google Drive/UAM/HUB/MobilityPatterns/Data")
source("C:/Users/wozni/OneDrive/Documents/GitHub/MobilityPatterns/scripts/od_pair_utils.R")
dir.create("../Figures", showWarnings = FALSE)

# =============================================================================
# Part 1 — attach population/workplace weights to itineraries
# =============================================================================

#Read itineraries produced by 05_read_itineraries.R
pt_itineraries  <- readRDS("pt_itineraries.rds")
car_itineraries <- readRDS("car_itineraries.rds")

#Read & prepare grids
pop_grid <- st_read("pop_grid.gpkg")
workplace_grid <- st_read("workplace_grid.gpkg")

workplace_grid <- st_transform(workplace_grid, crs = st_crs(pop_grid))

pop_grid$area <- st_area(pop_grid)
pop_grid <- setDT(pop_grid)[, .SD[which.max(area)], by=grid_id] #Remove cells with duplicate IDs on municipal boundaries
pop_grid <- st_as_sf(pop_grid)

# Collapse itineraries to one row per OD pair and compute PT/car ratios
# (shared with 07/09/10 -- see od_pair_utils.R). Renamed to this script's
# pre-existing column names (total_duration/total_distance/car_duration/
# car_distance/time_ratio) so itineraries_weights.csv's schema is unchanged.
od_combined <- build_od_comparison(pt_itineraries, car_itineraries) |>
  rename(
    total_duration = pt_duration_min,
    total_distance  = pt_distance_m,
    car_duration    = car_duration_min,
    car_distance    = car_distance_m,
    time_ratio      = tt_ratio
  )

# Origin weight — population
itineraries_pop <- od_combined |>
  st_as_sf(coords = c("from_lon", "from_lat"), crs = 4326) |>
  st_transform(st_crs(pop_grid)) |>
  st_join(pop_grid |> select(grid_id, working_age_pop), join = st_intersects) |>
  mutate(
    from_lon = st_coordinates(geometry)[, 1],  # ← extract before dropping
    from_lat = st_coordinates(geometry)[, 2]
  ) |>
  st_drop_geometry() |>
  filter(!is.na(working_age_pop))

cat("After pop join:", nrow(itineraries_pop), "rows\n")

# Destination weight — workplaces
# After the final st_drop_geometry(), add coordinates back explicitly
itineraries_weights <- itineraries_pop |>
  st_as_sf(coords = c("to_lon", "to_lat"), crs = 4326) |>
  st_transform(st_crs(workplace_grid)) |>
  st_join(workplace_grid |> select(workplaces), join = st_intersects) |>
  mutate(                              # ← extract coords before dropping
    to_lon = st_coordinates(geometry)[, 1],
    to_lat = st_coordinates(geometry)[, 2]
  ) |>
  st_drop_geometry() |>
  filter(!is.na(workplaces))

cat("After workplace join:", nrow(itineraries_weights), "rows\n")

write.csv(itineraries_weights, "itineraries_weights.csv", row.names = FALSE)

# =============================================================================
# Part 2 — explore the weighted travel-time ratios
# =============================================================================
# Uses itineraries_weights directly (in memory) rather than re-reading the
# CSV just written above.
itineraries <- itineraries_weights

# has_rail is already computed by build_od_comparison() in Part 1
# (has_rail = any(mode == "RAIL") per OD pair) -- reused directly here rather
# than re-deriving it from the `modes` string a second time.

#Calculate travel time ratios averaged by workplaces
w_ratio <- itineraries %>%
  group_by(from_id, working_age_pop) %>%
  summarise(weighted_ratio = weighted.mean(x = time_ratio, w = workplaces)) %>%
  arrange(weighted_ratio) %>%
  ungroup() %>%
  mutate(sum_pop = cumsum(working_age_pop))

#Only itineraries that include rail
w_ratio_rail <- itineraries %>%
  filter(has_rail == 1) %>%
  group_by(from_id, working_age_pop) %>%
  summarise(weighted_ratio = weighted.mean(x = time_ratio, w = workplaces)) %>%
  arrange(weighted_ratio) %>%
  ungroup() %>%
  mutate(sum_pop = cumsum(working_age_pop),
         rail = "rail")

#Other itineraries
w_ratio_other <- itineraries %>%
  filter(has_rail == 0) %>%
  group_by(from_id, working_age_pop) %>%
  summarise(weighted_ratio = weighted.mean(x = time_ratio, w = workplaces)) %>%
  arrange(weighted_ratio) %>%
  ungroup() %>%
  mutate(sum_pop = cumsum(working_age_pop),
         rail = "no rail")

w_ratio_combined <- rbind(w_ratio_rail, w_ratio_other)

#Plot histogram of travel time ratios averaged by workplaces and weighted by population
ggplot(w_ratio, aes(x = weighted_ratio, y = ..density.., weight = working_age_pop)) +
  geom_histogram() +
  labs(
    title = "Population-weighted distribution of PT/car travel-time ratio",
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Density (weighted by working-age population)"
  ) +
  theme_minimal()

ggsave("../Figures/Fig_travelratio_density.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_density.png\n")

#Only rail
ggplot(w_ratio_rail, aes(x = weighted_ratio, y = ..density.., weight = working_age_pop)) +
  geom_histogram() +
  labs(
    title = "Population-weighted PT/car ratio -- rail-served origins only",
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Density (weighted by working-age population)"
  ) +
  theme_minimal()

ggsave("../Figures/Fig_travelratio_density_rail.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_density_rail.png\n")

#Other
ggplot(w_ratio_other, aes(x = weighted_ratio, y = ..density.., weight = working_age_pop)) +
  geom_histogram() +
  labs(
    title = "Population-weighted PT/car ratio -- non-rail origins only",
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Density (weighted by working-age population)"
  ) +
  theme_minimal()

ggsave("../Figures/Fig_travelratio_density_norail.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_density_norail.png\n")

#Rail vs. other
# Dark theme (background #1a1a1a, white text/gridlines) added 2026-08-26 to
# match Figure 3's boxplots and the rest of the manuscript's dark-themed
# figures -- this pair (Figure 7) was still on theme_minimal().
ggplot(w_ratio_combined,
       aes(x = weighted_ratio,
           y = ..density..,
           weight = working_age_pop,
           colour = rail,
           fill = rail)) +
  geom_histogram(position = "identity", alpha = 0.65, linewidth = 0.6) +
  # Viridis stops shared with Figure 3's Car/PT palette (07_plot_itineraries.R)
  # for cross-figure coherence: rail has the lower (better) ratio, so it gets
  # the cooler low-value viridis stop; no-rail's higher ratio gets the warmer
  # high-value stop -- same convention as duration/distance there.
  scale_colour_manual(values = c(rail = "#9B59B6", "no rail" = "#FDE725")) +
  scale_fill_manual(values = c(rail = "#9B59B6", "no rail" = "#FDE725")) +
  labs(
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Density (weighted by working-age population)",
    colour = NULL, fill = NULL
  ) +
  theme_dark(base_size = 18) +
  theme(
    panel.background  = element_rect(fill = "#1a1a1a"),
    plot.background   = element_rect(fill = "#1a1a1a", colour = NA),
    legend.background = element_rect(fill = "#1a1a1a"),
    legend.key        = element_rect(fill = "#1a1a1a"),
    text              = element_text(color = "white"),
    axis.title        = element_text(size = 19, color = "white"),
    axis.text         = element_text(size = 18, color = "white"),
    legend.text       = element_text(size = 18, color = "white"),
    legend.position   = "top",
    panel.grid.major  = element_line(colour = "grey30"),
    panel.grid.minor  = element_blank()
  )

ggsave("../Figures/Fig_travelratio_density_rail_vs_norail.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_density_rail_vs_norail.png\n")

#Plot cumulative sum of population by workplace-averaged travel time ratio
working_age_pop_sum <- sum(w_ratio$working_age_pop)

#All
ggplot(w_ratio, aes(x = weighted_ratio, y = sum_pop/working_age_pop_sum)) +
  geom_line() +
  expand_limits(x = 0, y = 0) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Cumulative population share by PT/car travel-time ratio",
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Cumulative share of working-age population"
  ) +
  theme_minimal()

ggsave("../Figures/Fig_travelratio_cumulative_population.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_cumulative_population.png\n")

#Rail vs. no rail
# Dark theme, same rationale/palette as the histogram above.
ggplot(w_ratio_combined, aes(x = weighted_ratio, y = sum_pop/working_age_pop_sum, colour = rail)) +
  geom_line(linewidth = 1.4) +
  expand_limits(x = 0, y = 0) +
  scale_y_continuous(labels = scales::percent) +
  scale_colour_manual(values = c(rail = "#9B59B6", "no rail" = "#FDE725")) +
  labs(
    x = "Workplace-weighted PT/car travel-time ratio (per origin)",
    y = "Cumulative share of working-age population",
    colour = NULL
  ) +
  theme_dark(base_size = 18) +
  theme(
    panel.background  = element_rect(fill = "#1a1a1a"),
    plot.background   = element_rect(fill = "#1a1a1a", colour = NA),
    legend.background = element_rect(fill = "#1a1a1a"),
    legend.key        = element_rect(fill = "#1a1a1a"),
    text              = element_text(color = "white"),
    axis.title        = element_text(size = 19, color = "white"),
    axis.text         = element_text(size = 18, color = "white"),
    legend.text       = element_text(size = 18, color = "white"),
    legend.position   = "top",
    panel.grid.major  = element_line(colour = "grey30"),
    panel.grid.minor  = element_blank()
  )

ggsave("../Figures/Fig_travelratio_cumulative_population_rail_vs_norail.png", width = 8, height = 6, dpi = 300)
cat("Saved Figures/Fig_travelratio_cumulative_population_rail_vs_norail.png\n")

#Take a look at the most competitive itineraries
competitive <- itineraries %>% filter(time_ratio < 1.5)
competitive_by_muni <- table(competitive$county) %>% as.data.frame() %>% arrange(-Freq)
names(competitive_by_muni) <- c("county", "n_competitive_itineraries")
print(competitive_by_muni)
write.csv(competitive_by_muni, "competitive_by_municipality.csv", row.names = FALSE)

#Take a look at the least competitive itineraries (to be improved)
improvement <- itineraries %>% filter(time_ratio > 2.5)
improvement_by_muni <- table(improvement$county) %>% as.data.frame() %>% arrange(-Freq)
names(improvement_by_muni) <- c("county", "n_improvement_itineraries")
print(improvement_by_muni)
write.csv(improvement_by_muni, "improvement_by_municipality.csv", row.names = FALSE)

cat("\nSaved competitive_by_municipality.csv and improvement_by_municipality.csv\n")

#Identify high priority itineraries for improvement (?)
high_priority <- itineraries %>%
  filter(working_age_pop > quantile(working_age_pop, probs = 0.75)) %>%
  filter(workplaces > quantile(workplaces, probs = 0.75)) %>%
  filter(time_ratio > quantile(time_ratio, probs = 0.75))

# =============================================================================
# Part 3 — most/moderately/least competitive itineraries by route
# =============================================================================
# Restyled version of a Google-Drive-only exploratory script
# (explore_travel_ratios.R) that predates this file's 2026-07-27 merge --
# see the "TBD" this replaces, just above.
#
# DATA SOURCE (revised 2026-08-31): the current pipeline's own
# itineraries_weights.csv/`itineraries` (Part 1's output, one row per OD
# pair) dropped the per-itinerary `route`/`mode` comma-joined strings that
# script's Part 3 read directly. A first attempt reconstructed route
# composition from pt_itineraries.rds's segment-level data instead -- ran
# fine, but produced visibly different routes than the original reference
# figure (caught by the user comparing screenshots), because it was
# necessarily built from a *different, more recent* itinerary run than
# whatever produced the original script's data -- not a styling bug, a
# wrong-source-data bug. The ACTUAL original itineraries_weights.csv (one
# row per itinerary, `route`/`mode` comma-joined per segment e.g.
# "0,KW,KW,0,158,0" -- "0" for legs with no route id, i.e. WALK) was
# recovered from Downloads/ and copied to
# itineraries_weights_route_detail.csv, used ONLY here -- Parts 1/2 above
# are untouched and still use the current pipeline's own `itineraries`.
itineraries_route_detail <- read.csv("itineraries_weights_route_detail.csv")
itineraries_route_detail$weight <- itineraries_route_detail$working_age_pop * itineraries_route_detail$workplaces

# Same three competitiveness bands and cutoffs as the original script
# (< 1.5 / 1.5-2.5 / >= 2.5, matching the `competitive`/`improvement`
# filters a few lines up) and the same `separate_longer_delim()` explode-
# by-comma approach. Deliberately NOT taking the top 30 here yet -- see
# the bug note below.
route_weights_by_band <- itineraries_route_detail %>%
  mutate(band = case_when(
    time_ratio < 1.5 ~ "Most competitive",
    time_ratio < 2.5 ~ "Moderately competitive",
    TRUE              ~ "Least competitive"
  ) %>% factor(levels = c("Most competitive", "Moderately competitive", "Least competitive"))) %>%
  select(route, weight, band) %>%
  separate_longer_delim(route, delim = ",") %>%
  group_by(band, route) %>%
  summarise(sum_weight = sum(weight), .groups = "drop")

# GTFS route shapes -- ZTM only (bus/tram operator; rail route codes have
# no shape here, see note above)
gtfs_ztm      <- read_gtfs("gtfs/ztm.zip")
routes_shapes <- shapes_as_sf(gtfs_ztm$shapes)
trips_ztm     <- as.data.frame(gtfs_ztm$trips) %>% distinct(route_id, .keep_all = TRUE)
routes_shapes <- right_join(routes_shapes, trips_ztm, by = "shape_id") %>%
  st_transform(4326)

poz     <- st_read("poz.gpkg", quiet = TRUE)  # core-city boundary -- the only one drawn (see
poz_wgs <- st_transform(poz, 4326)            # below), matching every other figure in the
                                               # manuscript. The individual surrounding-municipality
                                               # borders from ap.gpkg were drawn briefly (2026-08-31,
                                               # matching the original script's `roi` layer exactly)
                                               # but removed per explicit follow-up request -- too
                                               # busy/cluttered against the routes. ap.gpkg itself is
                                               # still used below for the ROI filter/map extent, just
                                               # not drawn.
ap      <- st_read("ap.gpkg", quiet = TRUE)   # full agglomeration (25 municipalities)
ap_wgs  <- st_transform(ap, 4326)
roi_wgs <- st_union(ap_wgs)                   # dissolved -- ROI filter/extent only, not drawn

# BUG FOUND 2026-08-31 (user compared this figure's routes against the
# faithful tmap replication and they didn't match, even though both read
# the identical recovered CSV): the top-30 selection MUST happen AFTER
# joining to real GTFS shapes and filtering to the ROI, not before. The
# original script's own order (left_join -> st_filter(roi) ->
# subset(!is.na(sum_weight)) -> THEN slice_max(n=30)) matters: "0" (the
# WALK-leg placeholder token, present in nearly every single itinerary)
# and "KW"/"IC" (rail operator codes, no shape in ztm.zip) accumulate
# enormous cumulative weight simply by being ubiquitous, so taking the
# top 30 on the raw exploded token table let them soak up slots that
# should have gone to real bus/tram routes -- they'd only get dropped
# LATER for not matching a route_id, by which point a real route ranked
# 31st+ never got considered. Fixed by reordering: join + ROI-filter
# first, slice_max() last.
routes_by_band <- routes_shapes %>%
  inner_join(route_weights_by_band, by = c("route_id" = "route")) %>%
  st_filter(roi_wgs, .predicate = st_intersects) %>%
  group_by(band) %>%
  slice_max(order_by = sum_weight, n = 30) %>%
  ungroup()

# Full ap.gpkg extent, matching the original script's (uncropped) framing --
# reverted 2026-08-31 from an earlier tight, city-centred crop. That crop
# was tuned against the WRONG reconstructed route data (see Part 3's data-
# source note above); the correct routes, verified against the original
# script's own tmap output, fill this full extent well on their own, no
# need to crop anything off.
map_limits_routes <- st_bbox(roi_wgs) %>% st_as_sfc() %>% st_buffer(0.02) %>% st_bbox()

# Dark basemap: inverted Esri grey canvas only (no Overpass road-network
# overlay -- removed 2026-08-31 per explicit request; the grey terrain/
# water texture stays, just without the added primary/secondary/tertiary
# road lines). NOT CartoDB.DarkMatter (used by Figs 3/5/8) -- CARTO's free
# tile tier now requires an API key for anonymous requests (confirmed
# 2026-08-28, see README). Fetched at map_limits_routes -- the full
# ap.gpkg extent (see above) -- so resolution matches what's actually shown.
bbox_routes_3857 <- map_limits_routes %>% st_as_sfc() %>% st_transform(3857)
osm_tiles_routes <- get_tiles(bbox_routes_3857, provider = "Esri.WorldGrayCanvas", zoom = 11, crop = TRUE)
osm_bw_routes <- app(osm_tiles_routes, fun = function(x) {
  grey <- 0.299 * x[1] + 0.587 * x[2] + 0.114 * x[3]
  255 - grey
})
osm_bw_routes <- c(osm_bw_routes, osm_bw_routes, osm_bw_routes)

# Panel colours reuse Figure 5's PT-vs-car palette (09_OD_comparison.R:
# green = PT/competitive end, orange = intermediate, red = car-dominated
# end) for cross-figure consistency, rather than picking new colours.
band_colours_routes <- c(
  "Most competitive"       = "#2ecc71",
  "Moderately competitive" = "#e67e22",
  "Least competitive"      = "#c0392b"
)

make_route_competitiveness_map <- function(routes_sf, band_label) {
  ggplot() +
    geom_spatraster_rgb(data = osm_bw_routes, alpha = 0.75) +
    # Core-city (poz.gpkg) boundary only -- matches every other figure in
    # the manuscript. Drawing all 25 ap.gpkg municipal boundaries (matching
    # the original script's `roi` layer exactly) was tried first but
    # removed per explicit follow-up request (too cluttered).
    geom_sf(data = poz_wgs, fill = NA, colour = "white",
            linewidth = 0.4, inherit.aes = FALSE) +
    geom_sf(data = routes_sf, colour = band_colours_routes[[band_label]],
            linewidth = 0.9, alpha = 0.9, inherit.aes = FALSE) +
    coord_sf(crs = 4326, xlim = map_limits_routes[c("xmin", "xmax")],
             ylim = map_limits_routes[c("ymin", "ymax")]) +
    # Wrapped onto two lines rather than tuned to fit one -- a one-line
    # title at a legible size kept colliding with its neighbour whenever
    # patchwork's column widths shifted (e.g. when a fixed-aspect coord_sf
    # panel's actual rendered width changed, found 2026-08-28); a short
    # two-line title is robust to that regardless of exact column width.
    labs(title = paste0(band_label, " itineraries,\n30 top bus routes")) +
    theme_dark(base_size = 18) +
    theme(
      panel.background = element_rect(fill = "#1a1a1a"),
      plot.background  = element_rect(fill = "#1a1a1a", colour = NA),
      text             = element_text(color = "white"),
      axis.text        = element_blank(),
      axis.title       = element_blank(),
      axis.ticks       = element_blank(),
      axis.line        = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border     = element_blank(),
      # Title size increased 14 -> 20 and bolded per explicit request (2026-08-28).
      # Canvas widened to match (see ggsave below) -- at the old width=16 canvas,
      # size 22 titles overlapped between panels; still touched at the panel
      # edges at width=22 with no margin, so a small left/right plot.margin
      # gutter was added too. Tightened r/l 10 -> 2 per explicit follow-up
      # request (2026-08-31) for thinner spacing between panels -- titles are
      # now wrapped to two short lines (see labs(title=) above), so they no
      # longer need much horizontal breathing room to avoid colliding.
      plot.title       = element_text(size = 18, face = "bold", color = "white", hjust = 0.5, lineheight = 0.95),
      plot.margin      = margin(t = 5, r = 2, b = 5, l = 2)
    )
}

band_levels_routes <- levels(routes_by_band$band)
band_maps_routes <- setNames(lapply(band_levels_routes, function(b) {
  make_route_competitiveness_map(routes_by_band %>% filter(band == b), b)
}), band_levels_routes)

# plot_annotation(theme=) sets patchwork's OWN composite-level background
# (the gutters between panels and any leftover margin from coord_sf's
# fixed-aspect-ratio panel not exactly filling its slot) -- each panel's
# own plot.background (set inside make_route_competitiveness_map) only
# covers that panel's own rectangle, not patchwork's outer canvas, so
# without this the gutters render in patchwork's default white. Same root
# cause as the ggsave-canvas-vs-coord_sf-aspect-ratio mismatch documented
# for other map figures in this project, worse here because the tighter,
# non-square zoom bbox above makes the mismatch larger.
route_competitiveness_map <- (band_maps_routes[["Most competitive"]] +
  band_maps_routes[["Moderately competitive"]] +
  band_maps_routes[["Least competitive"]]) +
  plot_annotation(theme = theme(plot.background = element_rect(fill = "#1a1a1a", colour = NA)))

ggsave("../Figures/Fig_travelratio_route_competitiveness.png",
       plot = route_competitiveness_map, width = 24, height = 7, dpi = 300, bg = "#1a1a1a")
cat("\nSaved Figures/Fig_travelratio_route_competitiveness.png\n")
